name: neuro_dashboard
description: "A new Flutter project."
publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  page_manager:
    git:
      url: https://github.com/lucascardo12/page_manager.git
      ref: 0.0.3
  go_router: ^14.4.1
  sembast: ^3.7.5+2
  sembast_web: ^2.4.0+4
  uuid: ^4.5.1
  path: ^1.9.0
  path_provider: ^2.1.5
  dio: ^5.7.0
  get_it: ^7.7.0
  gusto_neumorphic: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true




